package games.jeopardy.server.entity;

import games.jeopardy.server.enums.GameStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * A single Jeopardy game session, from room creation through final scores.
 *
 * {@code Game} is the central aggregate of the domain. It owns the collections
 * of participating players ({@link GamePlayer}) and the board of clues
 * ({@link GameQuestion}). Real-time state (whose turn it is, the buzzer queue,
 * active timers) lives in Redis and is coordinated over WebSocket — only
 * durable, post-round state is flushed back here.
 *
 * Lifecycle:
 *   - Host calls the lobby API → {@code Game} created with status {@code WAITING}.
 *   - Host starts the game → status transitions to {@code IN_PROGRESS},
 *       {@code startedAt} is stamped, and the question board is populated.
 *   - All rounds complete → status transitions to {@code FINISHED},
 *       {@code finishedAt} is stamped, and player lifetime stats are updated.
 *
 * Room code: A short, human-friendly code (e.g. {@code "XKCD42"}) players
 * use to join via the lobby UI. Generated by the service layer, guaranteed unique.
 */
@Entity
@Table(name = "games")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Game {

    /**
     * Surrogate primary key. UUID generation is delegated to the database so the
     * key is available immediately after persistence.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /**
     * Short alphanumeric code players type to join the lobby (e.g. "XKCD42").
     * Generated by the service layer at room creation; must be unique across
     * all active games. Consider expiring codes after {@code FINISHED}/{@code ABANDONED}.
     */
    @Column(name = "room_code", nullable = false, unique = true, length = 10)
    private String roomCode;

    /**
     * Current lifecycle state. Drives which API operations are permitted —
     * e.g. only {@code WAITING} games accept new players; only {@code IN_PROGRESS}
     * games accept answer submissions.
     *
     * @see GameStatus
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    @Builder.Default
    private GameStatus status = GameStatus.WAITING;

    /**
     * Maximum number of players allowed in the lobby. Enforced during the join
     * flow — the service layer rejects join requests once this cap is reached.
     */
    @Column(name = "max_players", nullable = false)
    @Builder.Default
    private Integer maxPlayers = 6;

    /**
     * Tracks which Jeopardy round is currently active (1 = Jeopardy,
     * 2 = Double Jeopardy, 3 = Final Jeopardy). Used by the board-building
     * service to select the right set of {@link GameQuestion} records and to
     * double point values in round 2.
     */
    @Column(name = "current_round")
    @Builder.Default
    private Integer currentRound = 1;

    /**
     * The player who created the room. The host has elevated privileges:
     * starting the game, skipping unanswered clues, and ending the session early.
     * Lazily fetched — load explicitly only when host identity is needed.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "host_player_id")
    private Player host;

    /** Stamped when the host transitions the game from {@code WAITING} to {@code IN_PROGRESS}. */
    @Column(name = "started_at")
    private Instant startedAt;

    /** Stamped when the game reaches {@code FINISHED} or {@code ABANDONED}. */
    @Column(name = "finished_at")
    private Instant finishedAt;

    /** Set once on insert by Hibernate; tracks when the room was first created. */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private Instant createdAt;

    /** Refreshed by Hibernate on every update; useful for detecting stale sessions. */
    @UpdateTimestamp
    @Column(name = "updated_at")
    private Instant updatedAt;

    /**
     * Players participating in this game. Each entry holds the per-game score and
     * active status for one player. Use {@link GamePlayer#getScore()} for live
     * leaderboard data rather than reading from {@link Player#getTotalScore()},
     * which only updates at game end.
     */
    @OneToMany(mappedBy = "game", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<GamePlayer> gamePlayers = new ArrayList<>();

    /**
     * The set of clues placed on this game's board. Each entry records whether the
     * clue has been answered, who answered it, and whether the response was correct.
     * Query via {@link games.jeopardy.server.repository.GameQuestionRepository}
     * to fetch only unanswered clues or clues for a specific round.
     */
    @OneToMany(mappedBy = "game", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<GameQuestion> gameQuestions = new ArrayList<>();
}