package games.jeopardy.server.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Persistent account record for a registered Jeopardy player.
 *
 * A {@code Player} represents a user account that exists independently of any
 * individual game. Lifetime stats ({@code totalScore}, {@code gamesPlayed},
 * {@code gamesWon}) accumulate across all sessions and are updated when a
 * {@link Game} transitions to {@code FINISHED}.
 *
 * Relationships:
 * - {@code gamePlayers} — the join records linking this player to every game
 *       they have participated in. Use {@link GamePlayer} to access per-game scores.
 *
 * Security note: {@code passwordHash} stores a bcrypt digest — never the
 * raw password. Authentication logic lives in the service layer; this entity only
 * holds the persisted hash.
 */
@Entity
@Table(name = "players")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Player {

    /**
     * Surrogate primary key. Generated by the database via {@code GenerationType.UUID}
     * so the value is available immediately after {@code EntityManager.persist()}.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** Unique login handle chosen by the player. Used for authentication lookups. */
    @Column(name = "username", nullable = false, unique = true, length = 50)
    private String username;

    /** Public-facing name shown on the scoreboard during a live game. */
    @Column(name = "display_name", nullable = false, length = 100)
    private String displayName;

    /** Used for account recovery and notifications. Must be globally unique. */
    @Column(name = "email", nullable = false, unique = true, length = 255)
    private String email;

    /** bcrypt hash of the player's password. Never expose this in API responses. */
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    /** Running sum of points earned across all completed games. */
    @Column(name = "total_score")
    @Builder.Default
    private Long totalScore = 0L;

    /** Total number of games this player has participated in. */
    @Column(name = "games_played")
    @Builder.Default
    private Integer gamesPlayed = 0;

    /** Number of games where this player finished in first place. */
    @Column(name = "games_won")
    @Builder.Default
    private Integer gamesWon = 0;

    /** Set automatically by Hibernate on first insert; never changes afterward. */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private Instant createdAt;

    /** Refreshed by Hibernate on every update so we can audit recent activity. */
    @UpdateTimestamp
    @Column(name = "updated_at")
    private Instant updatedAt;

    /**
     * All game-participation records for this player. Lazily loaded by default
     * (Hibernate default for {@code @OneToMany}); fetch explicitly only when
     * building profile or history views to avoid N+1 queries.
     */
    @OneToMany(mappedBy = "player", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<GamePlayer> gamePlayers = new ArrayList<>();
}